const EDAMAM_CONFIG = {
    APP_ID: process.env.EXPO_PUBLIC_EDAMAM_APP_ID,
    APP_KEY: process.env.EXPO_PUBLIC_EDAMAM_APP_KEY,
    BASE_URL: process.env.EXPO_PUBLIC_EDAMAM_BASE_URL,
    AUTOCOMPLETE_URL: process.env.EXPO_PUBLIC_EDAMAM_AUTOCOMPLETE_URL,
};

export default EDAMAM_CONFIG;

